// ============================================================
// InterNexa — Constants & Static Data
// ============================================================

import type { Category, Internship, Mentor, LeaderboardEntry } from "@/types";

// ─── Internship Categories ──────────────────────────────────
export const CATEGORIES: Category[] = [
  { id: "1", name: "Artificial Intelligence", slug: "artificial-intelligence", icon: "Brain", description: "Build intelligent systems and neural networks", color: "text-violet-500", gradient: "from-violet-500 to-purple-600" },
  { id: "2", name: "Machine Learning", slug: "machine-learning", icon: "Cpu", description: "Master algorithms that learn from data", color: "text-blue-500", gradient: "from-blue-500 to-indigo-600" },
  { id: "3", name: "Data Science", slug: "data-science", icon: "BarChart3", description: "Extract insights from complex datasets", color: "text-emerald-500", gradient: "from-emerald-500 to-teal-600" },
  { id: "4", name: "Web Development", slug: "web-development", icon: "Globe", description: "Build modern web applications", color: "text-indigo-500", gradient: "from-indigo-500 to-blue-600" },
  { id: "5", name: "Python", slug: "python", icon: "Code2", description: "Master the world's most popular language", color: "text-yellow-500", gradient: "from-yellow-500 to-amber-600" },
  { id: "6", name: "Java", slug: "java", icon: "Coffee", description: "Enterprise-grade application development", color: "text-orange-500", gradient: "from-orange-500 to-red-600" },
  { id: "7", name: "React", slug: "react", icon: "Atom", description: "Build dynamic user interfaces", color: "text-cyan-500", gradient: "from-cyan-500 to-blue-600" },
  { id: "8", name: "Next.js", slug: "nextjs", icon: "Layers", description: "Full-stack React framework", color: "text-slate-500", gradient: "from-slate-500 to-slate-700" },
  { id: "9", name: "Node.js", slug: "nodejs", icon: "Server", description: "Server-side JavaScript runtime", color: "text-green-500", gradient: "from-green-500 to-emerald-600" },
  { id: "10", name: "Cybersecurity", slug: "cybersecurity", icon: "Shield", description: "Protect digital assets and systems", color: "text-red-500", gradient: "from-red-500 to-rose-600" },
  { id: "11", name: "Cloud Computing", slug: "cloud-computing", icon: "Cloud", description: "Master AWS, Azure, and GCP", color: "text-sky-500", gradient: "from-sky-500 to-blue-600" },
  { id: "12", name: "DevOps", slug: "devops", icon: "GitBranch", description: "CI/CD, Docker, and Kubernetes", color: "text-purple-500", gradient: "from-purple-500 to-violet-600" },
  { id: "13", name: "UI/UX Design", slug: "ui-ux-design", icon: "Palette", description: "Design beautiful user experiences", color: "text-pink-500", gradient: "from-pink-500 to-rose-600" },
  { id: "14", name: "Digital Marketing", slug: "digital-marketing", icon: "TrendingUp", description: "Master SEO, SEM, and social media", color: "text-amber-500", gradient: "from-amber-500 to-orange-600" },
  { id: "15", name: "Content Writing", slug: "content-writing", icon: "PenTool", description: "Create compelling digital content", color: "text-teal-500", gradient: "from-teal-500 to-cyan-600" },
  { id: "16", name: "Graphic Design", slug: "graphic-design", icon: "Figma", description: "Visual design and branding", color: "text-fuchsia-500", gradient: "from-fuchsia-500 to-pink-600" },
  { id: "17", name: "Video Editing", slug: "video-editing", icon: "Film", description: "Professional video production", color: "text-rose-500", gradient: "from-rose-500 to-red-600" },
  { id: "18", name: "Full Stack", slug: "full-stack", icon: "Layers", description: "End-to-end web development", color: "text-indigo-500", gradient: "from-indigo-500 to-violet-600" },
  { id: "19", name: "Frontend", slug: "frontend", icon: "Monitor", description: "Modern frontend development", color: "text-blue-500", gradient: "from-blue-500 to-cyan-600" },
  { id: "20", name: "Backend", slug: "backend", icon: "Database", description: "Server-side architecture", color: "text-green-500", gradient: "from-green-600 to-emerald-600" },
  { id: "21", name: "Blockchain", slug: "blockchain", icon: "Link", description: "Decentralized applications", color: "text-amber-500", gradient: "from-amber-500 to-yellow-600" },
  { id: "22", name: "Flutter", slug: "flutter", icon: "Smartphone", description: "Cross-platform mobile apps", color: "text-cyan-500", gradient: "from-cyan-500 to-teal-600" },
  { id: "23", name: "Android Development", slug: "android-development", icon: "Smartphone", description: "Native Android applications", color: "text-green-500", gradient: "from-green-500 to-lime-600" },
  { id: "24", name: "iOS Development", slug: "ios-development", icon: "Smartphone", description: "Native iOS applications", color: "text-slate-500", gradient: "from-slate-500 to-blue-600" },
  { id: "25", name: "Game Development", slug: "game-development", icon: "Gamepad2", description: "Create immersive games", color: "text-violet-500", gradient: "from-violet-500 to-indigo-600" },
  { id: "26", name: "Prompt Engineering", slug: "prompt-engineering", icon: "Sparkles", description: "Master AI prompt design", color: "text-yellow-500", gradient: "from-yellow-500 to-orange-500" },
  { id: "27", name: "Generative AI", slug: "generative-ai", icon: "Wand2", description: "Build with LLMs and diffusion models", color: "text-purple-500", gradient: "from-purple-500 to-pink-600" },
  { id: "28", name: "Finance", slug: "finance", icon: "DollarSign", description: "Financial analysis and modeling", color: "text-emerald-500", gradient: "from-emerald-500 to-green-600" },
  { id: "29", name: "Business Analytics", slug: "business-analytics", icon: "PieChart", description: "Data-driven business decisions", color: "text-blue-500", gradient: "from-blue-500 to-indigo-500" },
  { id: "30", name: "Human Resources", slug: "human-resources", icon: "Users", description: "People management and culture", color: "text-pink-500", gradient: "from-pink-500 to-fuchsia-600" },
  { id: "31", name: "C++", slug: "cpp", icon: "Code2", description: "Systems programming and DSA", color: "text-blue-600", gradient: "from-blue-600 to-indigo-700" },
  { id: "32", name: "Robotics", slug: "robotics", icon: "Bot", description: "Build intelligent robots", color: "text-slate-500", gradient: "from-slate-500 to-zinc-600" },
  { id: "33", name: "IoT", slug: "iot", icon: "Wifi", description: "Internet of Things solutions", color: "text-teal-500", gradient: "from-teal-500 to-emerald-600" },
  { id: "34", name: "AR/VR", slug: "ar-vr", icon: "Glasses", description: "Augmented and Virtual Reality", color: "text-purple-500", gradient: "from-purple-600 to-violet-600" },
  { id: "35", name: "Product Management", slug: "product-management", icon: "Layout", description: "Build and ship great products", color: "text-indigo-500", gradient: "from-indigo-500 to-blue-600" },
];

// ─── Featured Internships ───────────────────────────────────
export const FEATURED_INTERNSHIPS: Partial<Internship>[] = [
  {
    id: "1",
    title: "AI & Machine Learning Masterclass",
    slug: "ai-ml-masterclass",
    category: "Artificial Intelligence",
    shortDescription: "Build real AI projects with TensorFlow, PyTorch, and deploy production ML models.",
    duration: "90 Days",
    durationDays: 90,
    difficulty: "Intermediate",
    price: 2999,
    originalPrice: 7999,
    currency: "INR",
    rating: 4.9,
    totalRatings: 1247,
    totalEnrolled: 5420,
    seatsAvailable: 28,
    totalSeats: 100,
    isLive: true,
    isFeatured: true,
    isTrending: true,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"],
  },
  {
    id: "2",
    title: "Full Stack Web Development",
    slug: "full-stack-web-development",
    category: "Web Development",
    shortDescription: "Master React, Next.js, Node.js, and MongoDB to build production-ready apps.",
    duration: "60 Days",
    durationDays: 60,
    difficulty: "Beginner",
    price: 1999,
    originalPrice: 5999,
    currency: "INR",
    rating: 4.8,
    totalRatings: 2156,
    totalEnrolled: 8930,
    seatsAvailable: 45,
    totalSeats: 150,
    isLive: true,
    isFeatured: true,
    isTrending: true,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["React", "Next.js", "Node.js", "MongoDB", "TypeScript"],
  },
  {
    id: "3",
    title: "Data Science with Python",
    slug: "data-science-python",
    category: "Data Science",
    shortDescription: "Learn pandas, NumPy, scikit-learn, and real-world data analysis projects.",
    duration: "45 Days",
    durationDays: 45,
    difficulty: "Beginner",
    price: 1499,
    originalPrice: 4999,
    currency: "INR",
    rating: 4.7,
    totalRatings: 1890,
    totalEnrolled: 6750,
    seatsAvailable: 62,
    totalSeats: 200,
    isLive: true,
    isFeatured: true,
    isTrending: false,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn"],
  },
  {
    id: "4",
    title: "UI/UX Design Professional",
    slug: "ui-ux-design-professional",
    category: "UI/UX Design",
    shortDescription: "Master Figma, design systems, user research, and build a stunning portfolio.",
    duration: "30 Days",
    durationDays: 30,
    difficulty: "Beginner",
    price: 999,
    originalPrice: 3999,
    currency: "INR",
    rating: 4.8,
    totalRatings: 1456,
    totalEnrolled: 4200,
    seatsAvailable: 38,
    totalSeats: 100,
    isLive: false,
    isFeatured: true,
    isTrending: true,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["Figma", "Design Systems", "Prototyping", "User Research", "Wireframing"],
  },
  {
    id: "5",
    title: "Cybersecurity & Ethical Hacking",
    slug: "cybersecurity-ethical-hacking",
    category: "Cybersecurity",
    shortDescription: "Learn penetration testing, network security, and ethical hacking techniques.",
    duration: "90 Days",
    durationDays: 90,
    difficulty: "Advanced",
    price: 3999,
    originalPrice: 9999,
    currency: "INR",
    rating: 4.9,
    totalRatings: 876,
    totalEnrolled: 2340,
    seatsAvailable: 15,
    totalSeats: 50,
    isLive: true,
    isFeatured: true,
    isTrending: false,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["Kali Linux", "Burp Suite", "Nmap", "Wireshark", "Metasploit"],
  },
  {
    id: "6",
    title: "Generative AI & Prompt Engineering",
    slug: "generative-ai-prompt-engineering",
    category: "Generative AI",
    shortDescription: "Master ChatGPT, LLMs, Stable Diffusion, and build AI-powered applications.",
    duration: "45 Days",
    durationDays: 45,
    difficulty: "Intermediate",
    price: 2499,
    originalPrice: 6999,
    currency: "INR",
    rating: 4.9,
    totalRatings: 2340,
    totalEnrolled: 7890,
    seatsAvailable: 22,
    totalSeats: 100,
    isLive: true,
    isFeatured: true,
    isTrending: true,
    hasCertificate: true,
    hasProjects: true,
    hasMentorship: true,
    skills: ["ChatGPT", "LangChain", "LLMs", "Stable Diffusion", "Python"],
  },
];

// ─── Mentors ────────────────────────────────────────────────
export const MENTORS: Mentor[] = [
  {
    id: "1",
    name: "Dr. Arjun Mehta",
    avatar: "",
    title: "Senior AI Research Scientist",
    company: "Google DeepMind",
    companyLogo: "",
    bio: "10+ years in AI research with publications at NeurIPS, ICML, and ICLR.",
    expertise: ["Deep Learning", "NLP", "Computer Vision", "Reinforcement Learning"],
    experience: "10+ years",
    rating: 4.9,
    totalStudents: 2400,
    linkedin: "#",
    github: "#",
  },
  {
    id: "2",
    name: "Priya Sharma",
    avatar: "",
    title: "Staff Engineer",
    company: "Microsoft",
    companyLogo: "",
    bio: "Full-stack expert specializing in React, Node.js, and cloud architecture.",
    expertise: ["React", "Node.js", "Azure", "System Design"],
    experience: "8+ years",
    rating: 4.8,
    totalStudents: 3200,
    linkedin: "#",
    github: "#",
  },
  {
    id: "3",
    name: "Rahul Verma",
    avatar: "",
    title: "Data Science Lead",
    company: "Amazon",
    companyLogo: "",
    bio: "Leading ML teams building recommendation systems at scale.",
    expertise: ["Python", "ML", "Big Data", "AWS"],
    experience: "7+ years",
    rating: 4.7,
    totalStudents: 1800,
    linkedin: "#",
    github: "#",
  },
  {
    id: "4",
    name: "Sneha Patel",
    avatar: "",
    title: "Principal Designer",
    company: "Figma",
    companyLogo: "",
    bio: "Design leader with expertise in design systems and product design.",
    expertise: ["UI/UX", "Design Systems", "Figma", "Prototyping"],
    experience: "9+ years",
    rating: 4.9,
    totalStudents: 2100,
    linkedin: "#",
    github: "#",
  },
];

// ─── Testimonials ───────────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: "1",
    name: "Ananya Singh",
    avatar: "",
    role: "SDE Intern at Google",
    college: "IIT Delhi",
    rating: 5,
    comment: "InterNexa completely transformed my career. The AI/ML internship helped me land my dream role at Google. The mentors are incredible and the projects are industry-relevant.",
    internship: "AI & Machine Learning Masterclass",
  },
  {
    id: "2",
    name: "Rohan Kumar",
    avatar: "",
    role: "Frontend Developer at Flipkart",
    college: "NIT Trichy",
    rating: 5,
    comment: "The Full Stack internship was the best investment I made. Real projects, amazing mentors, and the certificate helped me stand out in interviews.",
    internship: "Full Stack Web Development",
  },
  {
    id: "3",
    name: "Meera Joshi",
    avatar: "",
    role: "Data Analyst at Deloitte",
    college: "BITS Pilani",
    rating: 5,
    comment: "From zero coding knowledge to landing a data analyst role — InterNexa made it possible. The structured curriculum and hands-on projects are unmatched.",
    internship: "Data Science with Python",
  },
  {
    id: "4",
    name: "Vikram Reddy",
    avatar: "",
    role: "Cybersecurity Analyst at Infosys",
    college: "VIT Vellore",
    rating: 5,
    comment: "The cybersecurity internship gave me practical skills that no college course could. I got certified and placed within 2 months of completion!",
    internship: "Cybersecurity & Ethical Hacking",
  },
  {
    id: "5",
    name: "Kavya Nair",
    avatar: "",
    role: "UI/UX Designer at Razorpay",
    college: "MIT Pune",
    rating: 5,
    comment: "InterNexa's design internship helped me build a portfolio that got me noticed by top companies. The mentor feedback was invaluable!",
    internship: "UI/UX Design Professional",
  },
  {
    id: "6",
    name: "Aditya Gupta",
    avatar: "",
    role: "ML Engineer at NVIDIA",
    college: "IIIT Hyderabad",
    rating: 5,
    comment: "The depth of the GenAI internship is incredible. I built 5 production-ready AI projects that impressed every interviewer.",
    internship: "Generative AI & Prompt Engineering",
  },
];

// ─── Statistics ─────────────────────────────────────────────
export const STATS = {
  totalStudents: 50000,
  totalInternships: 200,
  totalMentors: 150,
  placementRate: 94,
  averageSalaryHike: 180,
  companiesHiring: 500,
  countriesReached: 25,
  coursesCompleted: 120000,
};

// ─── Partner Companies ──────────────────────────────────────
export const PARTNER_COMPANIES = [
  "Google", "Microsoft", "Amazon", "Meta", "Apple",
  "Netflix", "Flipkart", "Razorpay", "Paytm", "CRED",
  "Zomato", "Swiggy", "Infosys", "TCS", "Wipro",
  "Deloitte", "Goldman Sachs", "Morgan Stanley", "Adobe", "Salesforce",
];

// ─── Internship Process Steps ───────────────────────────────
export const PROCESS_STEPS = [
  { step: 1, title: "Explore & Choose", description: "Browse 200+ internships across 35+ domains and find the perfect fit for your goals.", icon: "Search" },
  { step: 2, title: "Enroll & Learn", description: "Enroll instantly with secure payment. Start learning with video lectures and live sessions.", icon: "BookOpen" },
  { step: 3, title: "Build Projects", description: "Apply your skills on real-world projects with mentor guidance and AI-powered feedback.", icon: "Wrench" },
  { step: 4, title: "Get Certified", description: "Complete your internship and earn a verifiable certificate to boost your resume.", icon: "Award" },
  { step: 5, title: "Get Placed", description: "Leverage our placement support, resume builder, and company connections to land your dream job.", icon: "Rocket" },
];

// ─── FAQ Data ───────────────────────────────────────────────
export const FAQ_DATA = [
  { question: "What is InterNexa?", answer: "InterNexa is a premium AI-powered EdTech platform offering industry-relevant virtual internships across 35+ domains. We provide hands-on projects, expert mentorship, and verifiable certificates to help students launch their careers." },
  { question: "Are the internships recognized by companies?", answer: "Yes! Our internships are recognized by 500+ hiring partners. Each certificate comes with a unique ID and QR code for verification. Many of our alumni have been placed at top companies like Google, Microsoft, and Amazon." },
  { question: "Do I need prior experience?", answer: "Not at all! We offer internships at Beginner, Intermediate, and Advanced levels. Our beginner programs start from zero and guide you step-by-step with structured curriculum and mentor support." },
  { question: "How does the AI-powered learning work?", answer: "Our AI assistant helps you solve doubts instantly, analyzes your resume, conducts mock interviews, generates personalized learning roadmaps, and provides code reviews. It's like having a personal tutor available 24/7." },
  { question: "What about certificates?", answer: "Upon successful completion, you receive a premium digital certificate with a unique ID and QR verification code. Certificates can be downloaded as PDF, shared to LinkedIn, and added to your resume." },
  { question: "How are mentors selected?", answer: "Our mentors are industry professionals from top companies like Google, Microsoft, Amazon, and more. Each mentor goes through a rigorous selection process and has 5+ years of industry experience." },
  { question: "Is there placement support?", answer: "Absolutely! We provide resume building, mock interviews, LinkedIn optimization, and direct referrals to our 500+ hiring partners. Our placement rate is 94%." },
];

// ─── Leaderboard Mock Data ──────────────────────────────────
export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  { rank: 1, userId: "1", name: "Arjun Patel", avatar: "", xp: 15420, level: 28, internshipsCompleted: 8, streak: 45, badges: 24 },
  { rank: 2, userId: "2", name: "Sneha Reddy", avatar: "", xp: 14200, level: 26, internshipsCompleted: 7, streak: 38, badges: 21 },
  { rank: 3, userId: "3", name: "Ravi Kumar", avatar: "", xp: 13800, level: 25, internshipsCompleted: 7, streak: 32, badges: 19 },
  { rank: 4, userId: "4", name: "Priya Nair", avatar: "", xp: 12400, level: 23, internshipsCompleted: 6, streak: 28, badges: 17 },
  { rank: 5, userId: "5", name: "Vikash Singh", avatar: "", xp: 11900, level: 22, internshipsCompleted: 6, streak: 25, badges: 15 },
  { rank: 6, userId: "6", name: "Ananya Sharma", avatar: "", xp: 11200, level: 21, internshipsCompleted: 5, streak: 22, badges: 14 },
  { rank: 7, userId: "7", name: "Dev Mehta", avatar: "", xp: 10800, level: 20, internshipsCompleted: 5, streak: 20, badges: 13 },
  { rank: 8, userId: "8", name: "Kavya Gupta", avatar: "", xp: 10200, level: 19, internshipsCompleted: 5, streak: 18, badges: 12 },
  { rank: 9, userId: "9", name: "Rohit Jha", avatar: "", xp: 9800, level: 18, internshipsCompleted: 4, streak: 15, badges: 11 },
  { rank: 10, userId: "10", name: "Meera Das", avatar: "", xp: 9400, level: 17, internshipsCompleted: 4, streak: 12, badges: 10 },
];

// ─── Navigation Items ───────────────────────────────────────
export const NAV_ITEMS = [
  { label: "Internships", href: "/internships" },
  { label: "Categories", href: "/categories" },
  { label: "AI Tools", href: "/ai-tools" },
  { label: "Mentors", href: "/mentors" },
  { label: "Events", href: "/events" },
  { label: "Blog", href: "/blog" },
];

export const DASHBOARD_NAV = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "My Internships", href: "/dashboard/internships", icon: "GraduationCap" },
  { label: "My Courses", href: "/dashboard/courses", icon: "BookOpen" },
  { label: "Tasks & Attendance", href: "/dashboard/tasks", icon: "CheckSquare" },
  { label: "Assignments", href: "/dashboard/assignments", icon: "FileText" },
  { label: "Projects", href: "/dashboard/projects", icon: "FolderKanban" },
  { label: "Certificates", href: "/dashboard/certificates", icon: "Award" },
  { label: "Calendar", href: "/dashboard/calendar", icon: "Calendar" },
  { label: "Leaderboard", href: "/dashboard/leaderboard", icon: "Trophy" },
  { label: "AI Assistant", href: "/dashboard/ai-assistant", icon: "Bot" },
  { label: "Messages", href: "/dashboard/messages", icon: "MessageSquare" },
  { label: "Resume", href: "/dashboard/resume", icon: "FileUser" },
  { label: "Profile", href: "/dashboard/profile", icon: "User" },
  { label: "Settings", href: "/dashboard/settings", icon: "Settings" },
];

// ─── Duration Options ───────────────────────────────────────
export const DURATION_OPTIONS = [
  { label: "30 Days (1 Month)", value: "30", days: 30 },
  { label: "45 Days (1.5 Months)", value: "45", days: 45 },
  { label: "60 Days (2 Months)", value: "60", days: 60 },
  { label: "90 Days (3 Months)", value: "90", days: 90 },
  { label: "6 Months", value: "180", days: 180 },
];

// ─── Difficulty Options ─────────────────────────────────────
export const DIFFICULTY_OPTIONS = [
  { label: "Beginner", value: "beginner", color: "text-emerald-500" },
  { label: "Intermediate", value: "intermediate", color: "text-amber-500" },
  { label: "Advanced", value: "advanced", color: "text-red-500" },
];
