import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { supabaseAdmin } from "@/lib/supabase";
import { v4 as uuidv4 } from "uuid";

interface BaseDocumentData {
  documentId: string;
  applicationId: string;
  studentName: string;
  internshipName: string;
  date: string;
}

interface JoiningLetterData extends BaseDocumentData {
  duration: string;
  startDate: string;
}

interface CertificateData extends BaseDocumentData {
  grade: string;
  duration?: string;
}

async function uploadPdfToSupabase(pdfBuffer: Buffer, fileId: string): Promise<string> {
  // Ensure bucket exists or silently fail/continue if it does
  try {
    await supabaseAdmin.storage.createBucket('documents', { public: true });
  } catch (e) {
    // Bucket might already exist
  }

  const { error } = await supabaseAdmin.storage
    .from('documents')
    .upload(fileId, pdfBuffer, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (error) {
    console.error("PDF upload failed", error);
    throw error;
  }
  
  return fileId;
}

async function generateQRAndAdd(doc: jsPDF, verificationUrl: string) {
  try {
    const qrDataUrl = await QRCode.toDataURL(verificationUrl, { errorCorrectionLevel: 'H' });
    doc.addImage(qrDataUrl, 'PNG', 160, 250, 30, 30);
    doc.setFontSize(8);
    doc.text("Scan to verify", 175, 285, { align: "center" });
  } catch (error) {
    console.error("QR Generation failed", error);
  }
}

function addBrandingAndFooter(doc: jsPDF, documentId: string, title: string) {
  // Header Branding
  doc.setFont("helvetica", "bold");
  doc.setTextColor(79, 70, 229); // Indigo
  doc.setFontSize(28);
  doc.text("InterNexa", 20, 30);
  
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(10);
  doc.text("Bridge the Gap Between Learning and Leading", 20, 38);

  // Document Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text(title, 105, 55, { align: "center" });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Document ID: ${documentId}`, 20, 285);
  doc.text("Generated by InterNexa Automation System", 105, 285, { align: "center" });
}

export async function generateJoiningLetter(data: JoiningLetterData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF();
    
    addBrandingAndFooter(doc, data.documentId, "JOINING LETTER");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    
    doc.text(`Date: ${data.date}`, 145, 30);
    doc.text(`Ref: ${data.documentId}`, 145, 38);

    doc.text(`Dear ${data.studentName},`, 20, 80);
    
    const bodyText = `Welcome to InterNexa! We are thrilled to officially welcome you to the ${data.internshipName} internship program. This letter confirms your successful enrollment and onboarding.

Your internship will officially begin on ${data.startDate} and will span a duration of ${data.duration}.

During this period, you will have access to industry mentors, real-world projects, and our premium curriculum. We expect you to maintain a high standard of professionalism and dedicate the required hours to maximize your learning experience.

Please log in to your Student Dashboard to access your initial tasks and connect with your assigned mentor.`;

    const splitText = doc.splitTextToSize(bodyText, 170);
    doc.text(splitText, 20, 100);

    doc.setFont("helvetica", "bold");
    doc.text("Authorized Signature", 20, 220);
    doc.setFont("helvetica", "italic");
    doc.text("InterNexa HR Department", 20, 230);
    doc.text("Digitally Signed", 20, 240);

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexalabs.online'}/verify?id=${data.documentId}`;
    await generateQRAndAdd(doc, verificationUrl);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = `joining-letters/${data.applicationId}.pdf`;
    await uploadPdfToSupabase(pdfBuffer, fileId);

    return { success: true, fileId };
  } catch (error: any) {
    console.error("Joining letter generation failed:", error);
    return { success: false, error: error.message };
  }
}

export async function generateNDA(data: BaseDocumentData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF();
    addBrandingAndFooter(doc, data.documentId, "NON-DISCLOSURE AGREEMENT (NDA)");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    doc.text(`Date: ${data.date}`, 145, 30);
    
    const bodyText = `This Non-Disclosure Agreement is entered into between InterNexa and ${data.studentName} for the ${data.internshipName} program.

1. Confidential Information: The Intern agrees that all materials, code, proprietary processes, client data, and internal communications accessed during the internship are strictly confidential.
2. Non-Disclosure: The Intern shall not share, publish, or distribute any confidential information to third parties without prior written consent.
3. Term: The obligations of confidentiality shall remain in effect indefinitely after the completion of the internship.
4. Return of Materials: Upon completion, the Intern agrees to delete or return all confidential assets.

By accepting the offer and proceeding with the internship, the Intern digitally agrees to these terms.`;

    const splitText = doc.splitTextToSize(bodyText, 170);
    doc.text(splitText, 20, 80);

    doc.setFont("helvetica", "bold");
    doc.text(`Digitally Signed by: ${data.studentName}`, 20, 220);
    doc.setFont("helvetica", "italic");
    doc.text(`IP: Logged in System`, 20, 230);
    doc.text(`Timestamp: ${data.date}`, 20, 240);

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexalabs.online'}/verify?id=${data.documentId}`;
    await generateQRAndAdd(doc, verificationUrl);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = `ndas/${data.applicationId}.pdf`;
    await uploadPdfToSupabase(pdfBuffer, fileId);

    return { success: true, fileId };
  } catch (error: any) {
    console.error("NDA generation failed:", error);
    return { success: false, error: error.message };
  }
}

export async function generateCertificate(data: CertificateData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    // Certificate Border
    doc.setLineWidth(2);
    doc.setDrawColor(79, 70, 229);
    doc.rect(10, 10, 277, 190);
    doc.setLineWidth(0.5);
    doc.rect(12, 12, 273, 186);

    // Header Branding
    doc.setFont("times", "bold");
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(42);
    doc.text("InterNexa", 148, 40, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(26);
    doc.text("CERTIFICATE OF COMPLETION", 148, 65, { align: "center" });

    doc.setFont("times", "italic");
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text("This is to certify that", 148, 90, { align: "center" });

    doc.setFont("times", "bolditalic");
    doc.setFontSize(32);
    doc.setTextColor(79, 70, 229);
    doc.text(data.studentName, 148, 110, { align: "center" });

    doc.setFont("times", "normal");
    doc.setFontSize(14);
    doc.setTextColor(50, 50, 50);
    doc.text(`has successfully completed the ${data.internshipName} internship program`, 148, 125, { align: "center" });
    doc.text(`with a grade of ${data.grade}.`, 148, 135, { align: "center" });

    // --- Page 1: Certificate (Landscape) ---
    // Footer signatures
    
    // Director Signature
    doc.setFont("times", "italic");
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 100);
    doc.text("A. Sharma", 60, 168, { align: "center" });
    
    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("_______________________", 60, 170, { align: "center" });
    doc.text("Program Director", 60, 180, { align: "center" });

    // HR Signature
    doc.setFont("times", "italic");
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 100);
    doc.text("M. Verma", 237, 168, { align: "center" });

    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("_______________________", 237, 170, { align: "center" });
    doc.text("InterNexa HR", 237, 180, { align: "center" });

    // Certificate ID & Date & ISO Marks
    doc.setFont("times", "bold");
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("ISO 9001:2015 CERTIFIED | Govt. of India Recognized", 148, 195, { align: "center" });

    doc.setFont("times", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Certificate ID: ${data.documentId}`, 148, 180, { align: "center" });
    doc.text(`Date of Issue: ${data.date}`, 148, 185, { align: "center" });

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexalabs.online'}/verify?id=${data.documentId}`;
    let qrDataUrl = '';
    try {
      qrDataUrl = await QRCode.toDataURL(verificationUrl, { errorCorrectionLevel: 'H' });
      doc.addImage(qrDataUrl, 'PNG', 133, 145, 30, 30);
    } catch (e) {}

    // --- Page 2: Experience Letter (Portrait) ---
    doc.addPage("a4", "portrait");
    // Reuse addBrandingAndFooter equivalent for portrait
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(28);
    doc.text("InterNexa", 20, 30);
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(10);
    doc.text("Bridge the Gap Between Learning and Leading", 20, 38);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("EXPERIENCE LETTER", 105, 55, { align: "center" });
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Document ID: ${data.documentId}-EXP`, 20, 285);
    doc.text("Generated by InterNexa Automation System", 105, 285, { align: "center" });
    if (qrDataUrl) {
      doc.addImage(qrDataUrl, 'PNG', 160, 250, 30, 30);
      doc.text("Scan to verify", 175, 285, { align: "center" });
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Date: ${data.date}`, 145, 30);
    doc.text(`Ref: ${data.documentId}-EXP`, 145, 38);

    doc.text("To Whom It May Concern,", 20, 80);

    const expBody = `This is to certify that ${data.studentName} has successfully completed their internship program as a ${data.internshipName} Intern at InterNexa.

During their tenure of ${data.duration || 'the program'}, they have demonstrated excellent skills, professional demeanor, and a strong commitment to learning and delivering high-quality results. They have successfully completed all assigned industry-grade projects and assessments with a grade of ${data.grade}.

Their performance was outstanding, and they exhibited a deep understanding of core concepts in ${data.internshipName}. We found them to be hardworking, innovative, and a great team player.

We wish them all the best in their future endeavors.`;

    const expLines = doc.splitTextToSize(expBody, 170);
    doc.text(expLines, 20, 95);

    // Experience Letter Signatures
    doc.setFont("times", "italic");
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 100);
    doc.text("M. Verma", 20, 215);

    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("Authorized Signatory", 20, 220);
    doc.setFont("times", "italic");
    doc.text("Human Resources", 20, 226);
    doc.text("InterNexa Education", 20, 232);


    // --- Page 3: Letter of Recommendation (Portrait) ---
    doc.addPage("a4", "portrait");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(28);
    doc.text("InterNexa", 20, 30);
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(10);
    doc.text("Bridge the Gap Between Learning and Leading", 20, 38);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("LETTER OF RECOMMENDATION", 105, 55, { align: "center" });
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Document ID: ${data.documentId}-LOR`, 20, 285);
    doc.text("Generated by InterNexa Automation System", 105, 285, { align: "center" });
    if (qrDataUrl) {
      doc.addImage(qrDataUrl, 'PNG', 160, 250, 30, 30);
      doc.text("Scan to verify", 175, 285, { align: "center" });
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Date: ${data.date}`, 145, 30);
    doc.text(`Ref: ${data.documentId}-LOR`, 145, 38);

    doc.text("To Whom It May Concern,", 20, 80);

    const lorBody = `It is my absolute pleasure to highly recommend ${data.studentName} for any professional opportunities or advanced academic pursuits. 

During their time as a ${data.internshipName} Intern at InterNexa, they consistently showcased an exceptional work ethic and an impressive ability to grasp complex concepts quickly. Their dedication to completing tasks ahead of schedule while maintaining impeccable quality was truly remarkable. 

${data.studentName} is an incredibly motivated and talented individual. Their performance throughout the training and project implementation phases was stellar, culminating in a well-deserved grade of ${data.grade}. 

I have no doubt that ${data.studentName} will be a tremendous asset to any organization they join. I enthusiastically endorse their candidacy without reservation.`;

    const lorLines = doc.splitTextToSize(lorBody, 170);
    doc.text(lorLines, 20, 95);

    doc.setFont("helvetica", "bold");
    doc.text("Program Director", 20, 220);
    doc.setFont("helvetica", "italic");
    doc.text("InterNexa Mentorship Board", 20, 226);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = `certificates/${data.applicationId}.pdf`;
    await uploadPdfToSupabase(pdfBuffer, fileId);

    return { success: true, fileId };
  } catch (error: any) {
    console.error("Certificate generation failed:", error);
    return { success: false, error: error.message };
  }
}
