import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { supabaseAdmin } from "@/lib/supabase";
import { v4 as uuidv4 } from "uuid";

interface BaseDocumentData {
  documentId: string;
  studentName: string;
  internshipName: string;
  date: string;
}

interface JoiningLetterData extends BaseDocumentData {
  duration: string;
  startDate: string;
}

interface CertificateData extends BaseDocumentData {
  grade: string;
}

async function uploadPdfToSupabase(pdfBuffer: Buffer, folder: string): Promise<string> {
  const fileId = `${folder}/${uuidv4()}.pdf`;
  
  // Ensure bucket exists or silently fail/continue if it does
  try {
    await supabaseAdmin.storage.createBucket('documents', { public: true });
  } catch (e) {
    // Bucket might already exist
  }

  const { error } = await supabaseAdmin.storage
    .from('documents')
    .upload(fileId, pdfBuffer, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (error) {
    console.error("PDF upload failed", error);
    throw error;
  }
  
  return fileId;
}

async function generateQRAndAdd(doc: jsPDF, verificationUrl: string) {
  try {
    const qrDataUrl = await QRCode.toDataURL(verificationUrl, { errorCorrectionLevel: 'H' });
    doc.addImage(qrDataUrl, 'PNG', 160, 250, 30, 30);
    doc.setFontSize(8);
    doc.text("Scan to verify", 175, 285, { align: "center" });
  } catch (error) {
    console.error("QR Generation failed", error);
  }
}

function addBrandingAndFooter(doc: jsPDF, documentId: string, title: string) {
  // Header Branding
  doc.setFont("helvetica", "bold");
  doc.setTextColor(79, 70, 229); // Indigo
  doc.setFontSize(28);
  doc.text("InterNexa", 20, 30);
  
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(10);
  doc.text("Bridge the Gap Between Learning and Leading", 20, 38);

  // Document Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text(title, 105, 55, { align: "center" });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Document ID: ${documentId}`, 20, 285);
  doc.text("Generated by InterNexa Automation System", 105, 285, { align: "center" });
}

export async function generateJoiningLetter(data: JoiningLetterData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF();
    
    addBrandingAndFooter(doc, data.documentId, "JOINING LETTER");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    
    doc.text(`Date: ${data.date}`, 145, 30);
    doc.text(`Ref: ${data.documentId}`, 145, 38);

    doc.text(`Dear ${data.studentName},`, 20, 80);
    
    const bodyText = `Welcome to InterNexa! We are thrilled to officially welcome you to the ${data.internshipName} internship program. This letter confirms your successful enrollment and onboarding.

Your internship will officially begin on ${data.startDate} and will span a duration of ${data.duration}.

During this period, you will have access to industry mentors, real-world projects, and our premium curriculum. We expect you to maintain a high standard of professionalism and dedicate the required hours to maximize your learning experience.

Please log in to your Student Dashboard to access your initial tasks and connect with your assigned mentor.`;

    const splitText = doc.splitTextToSize(bodyText, 170);
    doc.text(splitText, 20, 100);

    doc.setFont("helvetica", "bold");
    doc.text("Authorized Signature", 20, 220);
    doc.setFont("helvetica", "italic");
    doc.text("InterNexa HR Department", 20, 230);
    doc.text("Digitally Signed", 20, 240);

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexa.vercel.app'}/verify?id=${data.documentId}`;
    await generateQRAndAdd(doc, verificationUrl);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = await uploadPdfToSupabase(pdfBuffer, 'joining-letters');

    return { success: true, fileId };
  } catch (error: any) {
    console.error("Joining letter generation failed:", error);
    return { success: false, error: error.message };
  }
}

export async function generateNDA(data: BaseDocumentData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF();
    addBrandingAndFooter(doc, data.documentId, "NON-DISCLOSURE AGREEMENT (NDA)");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    doc.text(`Date: ${data.date}`, 145, 30);
    
    const bodyText = `This Non-Disclosure Agreement is entered into between InterNexa and ${data.studentName} for the ${data.internshipName} program.

1. Confidential Information: The Intern agrees that all materials, code, proprietary processes, client data, and internal communications accessed during the internship are strictly confidential.
2. Non-Disclosure: The Intern shall not share, publish, or distribute any confidential information to third parties without prior written consent.
3. Term: The obligations of confidentiality shall remain in effect indefinitely after the completion of the internship.
4. Return of Materials: Upon completion, the Intern agrees to delete or return all confidential assets.

By accepting the offer and proceeding with the internship, the Intern digitally agrees to these terms.`;

    const splitText = doc.splitTextToSize(bodyText, 170);
    doc.text(splitText, 20, 80);

    doc.setFont("helvetica", "bold");
    doc.text(`Digitally Signed by: ${data.studentName}`, 20, 220);
    doc.setFont("helvetica", "italic");
    doc.text(`IP: Logged in System`, 20, 230);
    doc.text(`Timestamp: ${data.date}`, 20, 240);

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexa.vercel.app'}/verify?id=${data.documentId}`;
    await generateQRAndAdd(doc, verificationUrl);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = await uploadPdfToSupabase(pdfBuffer, 'ndas');

    return { success: true, fileId };
  } catch (error: any) {
    console.error("NDA generation failed:", error);
    return { success: false, error: error.message };
  }
}

export async function generateCertificate(data: CertificateData): Promise<{ success: boolean; fileId?: string; error?: string }> {
  try {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    // Certificate Border
    doc.setLineWidth(2);
    doc.setDrawColor(79, 70, 229);
    doc.rect(10, 10, 277, 190);
    doc.setLineWidth(0.5);
    doc.rect(12, 12, 273, 186);

    // Header Branding
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(40);
    doc.text("InterNexa", 148, 40, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(24);
    doc.text("CERTIFICATE OF COMPLETION", 148, 65, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text("This is to certify that", 148, 90, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(79, 70, 229);
    doc.text(data.studentName, 148, 110, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`has successfully completed the ${data.internshipName} internship program`, 148, 125, { align: "center" });
    doc.text(`with a grade of ${data.grade}.`, 148, 135, { align: "center" });

    // Footer signatures
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("_______________________", 60, 170, { align: "center" });
    doc.text("Program Director", 60, 180, { align: "center" });

    doc.text("_______________________", 237, 170, { align: "center" });
    doc.text("InterNexa HR", 237, 180, { align: "center" });

    // Certificate ID & Date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Certificate ID: ${data.documentId}`, 148, 180, { align: "center" });
    doc.text(`Date of Issue: ${data.date}`, 148, 185, { align: "center" });

    const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://internexa.vercel.app'}/verify?id=${data.documentId}`;
    try {
      const qrDataUrl = await QRCode.toDataURL(verificationUrl, { errorCorrectionLevel: 'H' });
      doc.addImage(qrDataUrl, 'PNG', 133, 145, 30, 30);
    } catch (e) {}

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const fileId = await uploadPdfToSupabase(pdfBuffer, 'certificates');

    return { success: true, fileId };
  } catch (error: any) {
    console.error("Certificate generation failed:", error);
    return { success: false, error: error.message };
  }
}
